name: Cleanup Workflow Runs
on:
  # ┌───────────── minute (0 - 59)
  # │ ┌───────────── hour (0 - 23)
  # │ │ ┌───────────── day of the month (1 - 31)
  # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  # │ │ │ │ │
  # │ │ │ │ │
  # │ │ │ │ │
  # * * * * *
  schedule:
    - cron: '35 22 * * *' # run at 22:35 UTC every day

  workflow_dispatch:
    inputs:
      #repository:
      #  description: 'Name of a repository or multiple as array string'
      #  required: true
      #  type: choice
      #  options:
      #    - '["org-parent", "org-parent-test", "reusable-gh-actions", "maven-cdi-plugin-utils", "unleash-maven-plugin", "unleash-scm-provider-git", "unleash-scm-provider-svn", "jenkins-unleash-plugin"]'
      #    - '["org-parent"]'
      #    - '["org-parent-test"]'
      #    - '["reusable-gh-actions"]'
      #    - '["maven-cdi-plugin-utils"]'
      #    - '["unleash-maven-plugin"]'
      #    - '["unleash-scm-provider-git"]'
      #    - '["unleash-scm-provider-svn"]'
      #    - '["jenkins-unleash-plugin"]'
      days:
        description: 'Days-worth of runs to keep for each workflow'
        required: true
        default: '0'
      minimum_runs:
        description: 'Minimum runs to keep for each workflow'
        required: true
        default: '1'
      delete_workflow_pattern:
        description: 'Name or filename of the workflow (if not set, all workflows are targeted)'
        required: false
      delete_workflow_by_state_pattern:
        description: 'Filter workflows by state: active, deleted, disabled_fork, disabled_inactivity, disabled_manually'
        required: true
        default: "ALL"
        type: choice
        options:
          - "ALL"
          - active
          - deleted
          - disabled_inactivity
          - disabled_manually
      delete_run_by_conclusion_pattern:
        description: 'Remove runs based on conclusion: action_required, cancelled, failure, skipped, success'
        required: true
        default: "ALL"
        type: choice
        options:
          - "ALL"
          - "Unsuccessful: action_required,cancelled,failure,skipped"
          - action_required
          - cancelled
          - failure
          - skipped
          - success
      dry_run:
        description: 'If not empty logs simulated changes only, no deletions are performed'
        required: false
        type: string

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    #strategy:
    #  matrix:
    #    repository: >-
    #      ${{
    #        startsWith(github.event.inputs.repository, '[')
    #        && fromJSON(github.event.inputs.repository)
    #        || github.event.inputs.repository
    #      }}
    steps:
      - name: Delete workflow runs (manually triggered)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: GHCICD/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          #repository: ${{ github.repository_owner }}/${{ matrix.repository }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs }}
          delete_workflow_pattern: ${{ github.event.inputs.delete_workflow_pattern }}
          delete_workflow_by_state_pattern: ${{ github.event.inputs.delete_workflow_by_state_pattern }}
          delete_run_by_conclusion_pattern: >-
            ${{
              startsWith(github.event.inputs.delete_run_by_conclusion_pattern, 'Unsuccessful:')
              && 'action_required,cancelled,failure,skipped'
              || github.event.inputs.delete_run_by_conclusion_pattern
            }}
          dry_run: ${{ github.event.inputs.dry_run }}

      - name: Delete workflow runs (triggered by schedule)
        if: ${{ github.event_name == 'schedule' }}
        uses: GHCICD/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          #repository: ${{ github.repository_owner }}/${{ matrix.repository }}
          repository: ${{ github.repository }}
          retain_days: '3'
          keep_minimum_runs: '0'
          delete_workflow_pattern: ''
          delete_workflow_by_state_pattern: 'ALL'
          delete_run_by_conclusion_pattern: 'ALL'
          dry_run: ''
