name: Test Maven Unleash E2E

on:
  workflow_dispatch:
        
  # ┌───────────── minute (0 - 59)
  # │ ┌───────────── hour (0 - 23)
  # │ │ ┌───────────── day of the month (1 - 31)
  # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  # │ │ │ │ │
  # │ │ │ │ │
  # │ │ │ │ │
  # * * * * *
  schedule:
    - cron: '17 7 * * *' # run at 7:17 UTC every day

  # NEVER enable push - this will run infinite for this workflow since of self re-triggering!
  #push:
    #branches:
    #  - 'test/unleash_e2e'

concurrency:
  # Ensure this workflow is running single at a time
  #group: ${{ github.workflow }}-${{ github.ref }}
  #group: ${{ github.workflow }}
  group: ${{ vars.UNLEASH_E2E_TEST_REF }}
  cancel-in-progress: false

# Following variables from vars context are being expected:
#   vars.UNLEASH_E2E_TEST_REF
#   vars.UNLEASH_E2E_TEST_RESET_REF
#   vars.UNLEASH_E2E_TEST_WORKFLOWS_BASE_URL

jobs:
  job_Validate_VarsAndTestBranch:
    name: Validate Vars And Test Ref
    if: github.ref == vars.UNLEASH_E2E_TEST_REF
    runs-on: ubuntu-latest
    steps:
      - name: Validate Expected Variables
        run: |
          echo "vars.UNLEASH_E2E_TEST_REF:                \"${{ vars.UNLEASH_E2E_TEST_REF }}\""
          echo "vars.UNLEASH_E2E_TEST_RESET_REF:          \"${{ vars.UNLEASH_E2E_TEST_RESET_REF }}\""
          echo "vars.UNLEASH_E2E_TEST_WORKFLOWS_BASE_URL: \"${{ vars.UNLEASH_E2E_TEST_WORKFLOWS_BASE_URL }}\""
          if [[    -z "${{ vars.UNLEASH_E2E_TEST_REF }}" \
                || -z "${{ vars.UNLEASH_E2E_TEST_RESET_REF }}" \
                || -z "${{ vars.UNLEASH_E2E_TEST_WORKFLOWS_BASE_URL }}" \
             ]]; then
            echo "### ERROR: At least one of the before listed variables is not set or it is not visible for this repo!"
            exit 1
          fi
      - name: Validate Running on Test Branch
        run: |
          echo "Expected ref: ${{ vars.UNLEASH_E2E_TEST_REF }}"
          echo "Actual ref:   ${{ github.ref }}"
          if [[ ! "${{ github.ref }}" == "${{ vars.UNLEASH_E2E_TEST_REF }}" ]]; then
            echo "### ERROR: This Action must run on ref ${{ vars.UNLEASH_E2E_TEST_REF }} only!"
            exit 1
          fi

  job_Reset_TestBranch:
    name: Reset Test Branch
    needs: job_Validate_VarsAndTestBranch
    runs-on: ubuntu-latest
    # Elevate permission on repo content to write to allow git pushing
    permissions:
      contents: write
    steps:
      - name: Checkout test branch
        uses: actions/checkout@v4
        with:
          # We need full history! - otherwise we end up in "missing commits" issue on unleash plugin
          fetch-depth: 0
          # Explicitly provide the ref path rather than using the original triggering SHA,
          # since that might have changed by particular jobs in multi job scenarios
          ref: ${{ github.ref }}
          token: ${{ secrets.SERVICE_USER_PAT }}
        
      - name: Force reset of test branch
        run: |
          git fetch --all
          RESET_COMMIT_SHA1=$(git log ${{ vars.UNLEASH_E2E_TEST_RESET_REF }} --max-count=1 --pretty=%H)
          git reset --hard ${RESET_COMMIT_SHA1}
          git push -f origin ${{ github.ref }}

  job_Test_Unleash_01:
    # Test 01 logScmProviderTagAndMsgPrefix.txt
    name: T01
    needs: job_Reset_TestBranch
    strategy:
      max-parallel: 1
      matrix:
        # use newer versions first
        javaVersion: [21, 17, 11, 8]
        mavenVersion: [3.9.8, 3.8.3, 3.6.3]
    # Elevate permission on repo content to write to allow git pushing
    permissions:
      contents: write
    secrets: inherit
    uses: mavenplugins/reusable-gh-actions/.github/workflows/__maven_unleash.yml@master
    with:
      runner: ubuntu-latest
      releaseToMavenCentral: false
      enforceUnleashReleaseWorkflow: false
      unleashWorkflowURL: ${{vars.UNLEASH_E2E_TEST_WORKFLOWS_BASE_URL }}/logScmProviderTagAndMsgPrefix.txt
      mavenVersion: ${{ matrix.mavenVersion }}
      mavenOpts: -Dversion.java=${{ matrix.javaVersion }}
      javaHomeVersion: ${{ matrix.javaVersion }}

  job_Test_Unleash_02:
    # Test 02 RollbackAfterTagScm
    name: T02
    needs: job_Test_Unleash_01
    strategy:
      max-parallel: 1
      matrix:
        # use newer versions first
        javaVersion: [21, 17, 11, 8]
        mavenVersion: [3.9.8, 3.8.3, 3.6.3]
    # Elevate permission on repo content to write to allow git pushing
    permissions:
      contents: write
    secrets: inherit
    uses: mavenplugins/reusable-gh-actions/.github/workflows/__maven_unleash.yml@master
    with:
      runner: ubuntu-latest
      releaseToMavenCentral: false
      enforceUnleashReleaseWorkflow: false
      unleashWorkflowURL: ${{vars.UNLEASH_E2E_TEST_WORKFLOWS_BASE_URL }}/performReleaseRollbackAfterTagScm.txt
      mavenVersion: ${{ matrix.mavenVersion }}
      mavenOpts: -Dversion.java=${{ matrix.javaVersion }}
      javaHomeVersion: ${{ matrix.javaVersion }}

  job_Test_Unleash_03:
    # Test 03 NoDeployRollbackAfterInstallArtifacts
    name: T03
    needs: job_Test_Unleash_02
    strategy:
      max-parallel: 1
      matrix:
        # use newer versions first
        javaVersion: [21, 17, 11, 8]
        mavenVersion: [3.9.8, 3.8.3, 3.6.3]
    # Elevate permission on repo content to write to allow git pushing
    permissions:
      contents: write
    secrets: inherit
    uses: mavenplugins/reusable-gh-actions/.github/workflows/__maven_unleash.yml@master
    with:
      runner: ubuntu-latest
      releaseToMavenCentral: false
      enforceUnleashReleaseWorkflow: false
      unleashWorkflowURL: ${{vars.UNLEASH_E2E_TEST_WORKFLOWS_BASE_URL }}/performReleaseNoDeployRollbackAfterInstallArtifacts.txt
      mavenVersion: ${{ matrix.mavenVersion }}
      mavenOpts: -Dversion.java=${{ matrix.javaVersion }}
      javaHomeVersion: ${{ matrix.javaVersion }}
